import { NextRequest, NextResponse } from 'next/server';
import {
  collection,
  getDocs,
  query,
  where,
  doc,
  updateDoc,
  addDoc,
  writeBatch,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { db, storage } from '@/lib/firebase';

// ─── Constants ────────────────────────────────────────────────────────────────

const RETENTION_DAYS = 15;

// ─── Security: only Vercel cron or our own secret can call this ───────────────

function isAuthorized(req: NextRequest): boolean {
  // Vercel sets this header on cron invocations
  const cronSecret = req.headers.get('authorization');
  const expectedSecret = `Bearer ${process.env.CRON_SECRET}`;

  // Also allow Vercel's internal cron header
  const vercelCron = req.headers.get('x-vercel-cron');

  if (vercelCron === '1') return true;
  if (process.env.CRON_SECRET && cronSecret === expectedSecret) return true;

  // In development, allow without auth
  if (process.env.NODE_ENV === 'development') return true;

  return false;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function tsToDate(ts: unknown): Date {
  if (ts instanceof Timestamp) return ts.toDate();
  if (typeof ts === 'string') return new Date(ts);
  return new Date();
}

function generateReportHTML(data: {
  businessName: string;
  periodStart: Date;
  periodEnd: Date;
  totalScans: number;
  totalClicks: number;
  conversionRate: number;
  generatedAt: Date;
}): string {
  const fmt = (d: Date) =>
    d.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>ReviewKaro Report — ${data.businessName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #111; background: #fff; padding: 40px; }
    .header { border-bottom: 3px solid #7c3aed; padding-bottom: 20px; margin-bottom: 28px; }
    .logo { font-size: 20px; font-weight: 700; color: #7c3aed; }
    .title { font-size: 26px; font-weight: 700; margin-top: 6px; }
    .subtitle { color: #6b7280; font-size: 13px; margin-top: 3px; }
    .period { background: #f5f3ff; border-radius: 8px; padding: 10px 14px; margin-bottom: 24px; font-size: 13px; color: #5b21b6; }
    .notice { background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 10px 14px; margin-bottom: 24px; font-size: 12px; color: #92400e; }
    .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; margin-bottom: 28px; }
    .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 18px; text-align: center; }
    .stat-value { font-size: 32px; font-weight: 700; color: #7c3aed; }
    .stat-label { font-size: 11px; color: #6b7280; margin-top: 3px; text-transform: uppercase; letter-spacing: 0.05em; }
    .footer { margin-top: 36px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">ReviewKaro</div>
    <div class="title">${data.businessName}</div>
    <div class="subtitle">Automated Analytics Report</div>
  </div>
  <div class="period">📅 Period: ${fmt(data.periodStart)} — ${fmt(data.periodEnd)}</div>
  <div class="notice">⚠️ Raw activity logs are stored for ${RETENTION_DAYS} days only. This report is saved permanently.</div>
  <div class="stats">
    <div class="stat"><div class="stat-value">${data.totalScans}</div><div class="stat-label">QR Scans</div></div>
    <div class="stat"><div class="stat-value">${data.totalClicks}</div><div class="stat-label">Review Clicks</div></div>
    <div class="stat"><div class="stat-value">${data.conversionRate}%</div><div class="stat-label">Conversion Rate</div></div>
  </div>
  <div class="footer">
    Auto-generated by ReviewKaro on ${data.generatedAt.toLocaleString('en-IN')}<br/>
    Reports are stored permanently. Raw logs deleted after ${RETENTION_DAYS} days.
  </div>
</body>
</html>`;
}

// ─── Core retention logic for one business ────────────────────────────────────

async function processBusinessRetention(businessId: string, businessName: string, ownerUid: string): Promise<{
  businessId: string;
  status: 'success' | 'skipped' | 'error';
  scansDeleted: number;
  clicksDeleted: number;
  reportId?: string;
  error?: string;
}> {
  try {
    const now = new Date();
    const cutoff = new Date(now.getTime() - RETENTION_DAYS * 24 * 60 * 60 * 1000);

    // ── 1. Fetch ALL logs for this business ──
    const [scanSnap, clickSnap] = await Promise.all([
      getDocs(query(collection(db, 'scan_logs'), where('businessId', '==', businessId))),
      getDocs(query(collection(db, 'review_clicks'), where('businessId', '==', businessId))),
    ]);

    // Separate into: within retention window vs old (to delete)
    const recentScans = scanSnap.docs.filter((d) => tsToDate(d.data().timestamp) >= cutoff);
    const oldScans    = scanSnap.docs.filter((d) => tsToDate(d.data().timestamp) < cutoff);
    const recentClicks = clickSnap.docs.filter((d) => tsToDate(d.data().timestamp) >= cutoff);
    const oldClicks    = clickSnap.docs.filter((d) => tsToDate(d.data().timestamp) < cutoff);

    // Skip if nothing to delete
    if (oldScans.length === 0 && oldClicks.length === 0) {
      return { businessId, status: 'skipped', scansDeleted: 0, clicksDeleted: 0 };
    }

    // ── 2. Compute stats for the retention window ──
    const totalScans  = recentScans.length;
    const totalClicks = recentClicks.length;
    const conversionRate = totalScans > 0 ? Math.round((totalClicks / totalScans) * 100) : 0;

    // ── 3. Generate HTML report ──
    const html = generateReportHTML({
      businessName,
      periodStart: cutoff,
      periodEnd: now,
      totalScans,
      totalClicks,
      conversionRate,
      generatedAt: now,
    });

    // ── 4. Upload to Firebase Storage ──
    const fileName = `reports/${ownerUid}/${businessId}/${now.getTime()}.html`;
    const storageRef = ref(storage, fileName);
    const blob = new Blob([html], { type: 'text/html' });
    await uploadBytes(storageRef, blob, { contentType: 'text/html' });
    const pdfUrl = await getDownloadURL(storageRef);

    // ── 5. Save report record to Firestore ──
    const reportRef = await addDoc(collection(db, 'reports'), {
      businessId,
      businessName,
      ownerUid,
      periodStart: cutoff.toISOString(),
      periodEnd: now.toISOString(),
      totalScans,
      totalClicks,
      conversionRate,
      pdfUrl,
      generatedAt: serverTimestamp(),
    });

    // ── 6. Update business retention fields ──
    const nextDeletion = new Date(now.getTime() + RETENTION_DAYS * 24 * 60 * 60 * 1000);
    await updateDoc(doc(db, 'businesses', businessId), {
      lastReportGeneratedAt: serverTimestamp(),
      nextDeletionDate: nextDeletion.toISOString(),
      updatedAt: serverTimestamp(),
    });

    // ── 7. Delete old logs in batches (Firestore batch limit = 500) ──
    const toDelete = [...oldScans, ...oldClicks];
    for (let i = 0; i < toDelete.length; i += 400) {
      const batch = writeBatch(db);
      toDelete.slice(i, i + 400).forEach((d) => batch.delete(d.ref));
      await batch.commit();
    }

    console.log(
      `[retention] ✅ ${businessName}: report=${reportRef.id}, deleted ${oldScans.length} scans + ${oldClicks.length} clicks`
    );

    return {
      businessId,
      status: 'success',
      scansDeleted: oldScans.length,
      clicksDeleted: oldClicks.length,
      reportId: reportRef.id,
    };
  } catch (err) {
    console.error(`[retention] ❌ ${businessName}:`, err);
    return {
      businessId,
      status: 'error',
      scansDeleted: 0,
      clicksDeleted: 0,
      error: (err as Error).message,
    };
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function GET(req: NextRequest) {
  if (!isAuthorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const startTime = Date.now();
  console.log('[retention] Cron job started at', new Date().toISOString());

  try {
    // Fetch all active businesses
    const bizSnap = await getDocs(
      query(collection(db, 'businesses'), where('active', '==', true))
    );

    if (bizSnap.empty) {
      return NextResponse.json({ message: 'No active businesses found', processed: 0 });
    }

    const results = [];

    // Process each business sequentially to avoid overwhelming Firestore
    for (const bizDoc of bizSnap.docs) {
      const data = bizDoc.data();
      const result = await processBusinessRetention(
        bizDoc.id,
        data.name || 'Unknown',
        data.ownerUid || ''
      );
      results.push(result);
    }

    const summary = {
      processed: results.length,
      success: results.filter((r) => r.status === 'success').length,
      skipped: results.filter((r) => r.status === 'skipped').length,
      errors: results.filter((r) => r.status === 'error').length,
      totalScansDeleted: results.reduce((s, r) => s + r.scansDeleted, 0),
      totalClicksDeleted: results.reduce((s, r) => s + r.clicksDeleted, 0),
      durationMs: Date.now() - startTime,
      timestamp: new Date().toISOString(),
    };

    console.log('[retention] Cron job completed:', summary);
    return NextResponse.json(summary);
  } catch (err) {
    console.error('[retention] Cron job failed:', err);
    return NextResponse.json(
      { error: 'Cron job failed', details: (err as Error).message },
      { status: 500 }
    );
  }
}

// Also support POST for manual triggers from dashboard
export async function POST(req: NextRequest) {
  return GET(req);
}
