import {
  collection,
  addDoc,
  getDocs,
  query,
  where,
  orderBy,
  limit,
  deleteDoc,
  doc,
  updateDoc,
  serverTimestamp,
  Timestamp,
  writeBatch,
} from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { db, storage } from '@/lib/firebase';
import { BusinessReport } from '@/types';
import { getScanLogs, getReviewClicks } from './logService';

export const RETENTION_DAYS = 15;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function tsToIso(ts: unknown): string {
  if (ts instanceof Timestamp) return ts.toDate().toISOString();
  if (typeof ts === 'string') return ts;
  return new Date().toISOString();
}

/** Days remaining until nextDeletionDate. Returns null if not set. */
export function getDaysUntilDeletion(nextDeletionDate?: string): number | null {
  if (!nextDeletionDate) return null;
  const diff = new Date(nextDeletionDate).getTime() - Date.now();
  return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}

/** Urgency level for the countdown banner */
export function getRetentionUrgency(daysLeft: number | null): 'red' | 'orange' | 'blue' | null {
  if (daysLeft === null) return null;
  if (daysLeft <= 3) return 'red';
  if (daysLeft <= 7) return 'orange';
  return 'blue';
}

// ─── PDF Generation (client-side, no external lib needed) ────────────────────

/**
 * Generates a simple PDF report as a Blob using the browser's print API.
 * For production, replace with jsPDF or a server-side PDF generator.
 */
export function generatePDFBlob(report: {
  businessName: string;
  periodStart: string;
  periodEnd: string;
  totalScans: number;
  totalClicks: number;
  conversionRate: number;
  generatedAt: string;
}): Blob {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>ReviewKaro Report — ${report.businessName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #111; background: #fff; padding: 40px; }
    .header { border-bottom: 3px solid #7c3aed; padding-bottom: 20px; margin-bottom: 32px; }
    .logo { font-size: 22px; font-weight: 700; color: #7c3aed; }
    .title { font-size: 28px; font-weight: 700; margin-top: 8px; }
    .subtitle { color: #6b7280; font-size: 14px; margin-top: 4px; }
    .period { background: #f5f3ff; border-radius: 8px; padding: 12px 16px; margin-bottom: 32px; font-size: 13px; color: #5b21b6; }
    .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px; }
    .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px; text-align: center; }
    .stat-value { font-size: 36px; font-weight: 700; color: #7c3aed; }
    .stat-label { font-size: 12px; color: #6b7280; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.05em; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
    .retention-note { background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; font-size: 13px; color: #92400e; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">ReviewKaro</div>
    <div class="title">${report.businessName}</div>
    <div class="subtitle">Analytics Report</div>
  </div>

  <div class="period">
    📅 Report Period: ${new Date(report.periodStart).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
    — ${new Date(report.periodEnd).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
  </div>

  <div class="retention-note">
    ⚠️ Raw activity logs are stored for ${RETENTION_DAYS} days only. This PDF report is saved permanently.
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-value">${report.totalScans}</div>
      <div class="stat-label">QR Scans</div>
    </div>
    <div class="stat">
      <div class="stat-value">${report.totalClicks}</div>
      <div class="stat-label">Review Clicks</div>
    </div>
    <div class="stat">
      <div class="stat-value">${report.conversionRate}%</div>
      <div class="stat-label">Conversion Rate</div>
    </div>
  </div>

  <div class="footer">
    Generated by ReviewKaro on ${new Date(report.generatedAt).toLocaleString('en-IN')}
    <br />Reports are stored permanently. Raw logs are deleted after ${RETENTION_DAYS} days.
  </div>
</body>
</html>`;

  return new Blob([html], { type: 'text/html' });
}

// ─── Report CRUD ──────────────────────────────────────────────────────────────

/** Fetch all reports for a business, newest first */
export async function getReportsForBusiness(businessId: string): Promise<BusinessReport[]> {
  const q = query(
    collection(db, 'reports'),
    where('businessId', '==', businessId),
    limit(50)
  );
  const snap = await getDocs(q);
  const reports = snap.docs.map((d) => {
    const data = d.data();
    return {
      id: d.id,
      businessId: data.businessId,
      businessName: data.businessName,
      ownerUid: data.ownerUid,
      periodStart: tsToIso(data.periodStart),
      periodEnd: tsToIso(data.periodEnd),
      totalScans: data.totalScans || 0,
      totalClicks: data.totalClicks || 0,
      conversionRate: data.conversionRate || 0,
      pdfUrl: data.pdfUrl || '',
      generatedAt: tsToIso(data.generatedAt),
    } as BusinessReport;
  });
  return reports.sort(
    (a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
  );
}

/** Fetch all reports for an owner across all businesses */
export async function getReportsForOwner(ownerUid: string): Promise<BusinessReport[]> {
  const q = query(
    collection(db, 'reports'),
    where('ownerUid', '==', ownerUid),
    limit(100)
  );
  const snap = await getDocs(q);
  const reports = snap.docs.map((d) => {
    const data = d.data();
    return {
      id: d.id,
      businessId: data.businessId,
      businessName: data.businessName,
      ownerUid: data.ownerUid,
      periodStart: tsToIso(data.periodStart),
      periodEnd: tsToIso(data.periodEnd),
      totalScans: data.totalScans || 0,
      totalClicks: data.totalClicks || 0,
      conversionRate: data.conversionRate || 0,
      pdfUrl: data.pdfUrl || '',
      generatedAt: tsToIso(data.generatedAt),
    } as BusinessReport;
  });
  return reports.sort(
    (a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
  );
}

// ─── Core retention job (runs client-side, triggered manually or on schedule) ─

/**
 * Generate a PDF report for a business, upload to Storage, save to Firestore,
 * update business retention fields, then delete old logs.
 *
 * SAFETY: Deletion only happens AFTER PDF is successfully uploaded.
 */
export async function runRetentionForBusiness(
  businessId: string,
  businessName: string,
  ownerUid: string
): Promise<{ success: boolean; reportId?: string; error?: string }> {
  try {
    const now = new Date();
    const endDate = now;
    const startDate = new Date(now.getTime() - RETENTION_DAYS * 24 * 60 * 60 * 1000);

    // 1. Fetch logs for the retention window
    const [scans, clicks] = await Promise.all([
      getScanLogs(businessId),
      getReviewClicks(businessId),
    ]);

    // Filter to retention window
    const windowScans = scans.filter(
      (s) => new Date(s.timestamp) >= startDate && new Date(s.timestamp) <= endDate
    );
    const windowClicks = clicks.filter(
      (c) => new Date(c.timestamp) >= startDate && new Date(c.timestamp) <= endDate
    );

    const totalScans = windowScans.length;
    const totalClicks = windowClicks.length;
    const conversionRate =
      totalScans > 0 ? Math.round((totalClicks / totalScans) * 100) : 0;

    // 2. Generate PDF blob
    const reportData = {
      businessName,
      periodStart: startDate.toISOString(),
      periodEnd: endDate.toISOString(),
      totalScans,
      totalClicks,
      conversionRate,
      generatedAt: now.toISOString(),
    };
    const pdfBlob = generatePDFBlob(reportData);

    // 3. Upload to Firebase Storage
    const fileName = `reports/${ownerUid}/${businessId}/${now.getTime()}.html`;
    const storageRef = ref(storage, fileName);
    await uploadBytes(storageRef, pdfBlob, { contentType: 'text/html' });
    const pdfUrl = await getDownloadURL(storageRef);

    // 4. Save report to Firestore
    const reportRef = await addDoc(collection(db, 'reports'), {
      businessId,
      businessName,
      ownerUid,
      periodStart: startDate.toISOString(),
      periodEnd: endDate.toISOString(),
      totalScans,
      totalClicks,
      conversionRate,
      pdfUrl,
      generatedAt: serverTimestamp(),
    });

    // 5. Update business retention fields
    const nextDeletion = new Date(now.getTime() + RETENTION_DAYS * 24 * 60 * 60 * 1000);
    await updateDoc(doc(db, 'businesses', businessId), {
      lastReportGeneratedAt: serverTimestamp(),
      nextDeletionDate: nextDeletion.toISOString(),
      updatedAt: serverTimestamp(),
    });

    // 6. Delete old logs (ONLY after PDF success)
    const cutoff = startDate.toISOString();
    await deleteOldLogs(businessId, cutoff);

    return { success: true, reportId: reportRef.id };
  } catch (err) {
    console.error('[retention] Failed for business', businessId, err);
    return { success: false, error: (err as Error).message };
  }
}

/**
 * Delete scan_logs and review_clicks older than the cutoff date for a business.
 * Uses client-side filtering since we can't do range queries without composite indexes.
 */
async function deleteOldLogs(businessId: string, cutoffIso: string): Promise<void> {
  const cutoff = new Date(cutoffIso);

  // Fetch all logs for this business
  const [scanSnap, clickSnap] = await Promise.all([
    getDocs(query(collection(db, 'scan_logs'), where('businessId', '==', businessId))),
    getDocs(query(collection(db, 'review_clicks'), where('businessId', '==', businessId))),
  ]);

  // Batch delete old ones
  const batch = writeBatch(db);
  let count = 0;

  scanSnap.docs.forEach((d) => {
    const ts = d.data().timestamp;
    const date = ts instanceof Timestamp ? ts.toDate() : new Date(ts);
    if (date < cutoff) {
      batch.delete(d.ref);
      count++;
    }
  });

  clickSnap.docs.forEach((d) => {
    const ts = d.data().timestamp;
    const date = ts instanceof Timestamp ? ts.toDate() : new Date(ts);
    if (date < cutoff) {
      batch.delete(d.ref);
      count++;
    }
  });

  if (count > 0) {
    await batch.commit();
    console.log(`[retention] Deleted ${count} old log entries for business ${businessId}`);
  }
}
